sensor:
- platform: template
  sensors:
    network_wireless_clients:
      friendly_name: "Network - Wireless Clients"
      unique_id: "network_wireless_clients"
      icon_template: "mdi:access-point-network"
      value_template: >
        {% set main = states.device_tracker | selectattr('attributes.essid', 'defined') | selectattr('attributes.essid', 'eq', "Brampton") | list | count %}
        {% set iot = states.device_tracker | selectattr('attributes.essid', 'defined') | selectattr('attributes.essid', 'eq', "Brampton - IoT") | list | count %}
        {{ main + iot }}