# Set up lighting groups
light:
- platform: group
  name: Master Suite - Lights
  unique_id: light_group_master_suite_all
  entities:
    - light.master_bedroom_main_lights
    - light.master_bedroom_entrance_lights
    - light.master_bedroom_side_lights
    - light.master_dressing_room_main_lights
    - light.master_bathroom_main_lights