automation:
- id: hot_tub_initialise_target_temp
  alias: Hot Tub - Initialise 'input_number.hot_tub_target_temp' on HA startup
  trigger:
    - platform: homeassistant
      event: start
    - platform: numeric_state
      entity_id: sensor.hot_tub_temp_target
      above: input_number.hot_tub_target_temp
    - platform: numeric_state
      entity_id: sensor.hot_tub_temp_target
      below: input_number.hot_tub_target_temp
  action:
    service: input_number.set_value
    data_template:
      entity_id: input_number.hot_tub_target_temp
      value: "{{ states('sensor.hot_tub_temp_target') | int }}"    