automation: 
- id: hot_tub_set_target_temp
  alias: Hot Tub - Set target temperature on change of 'input_number.hot_tub_target_temp'
  trigger:
    platform: state
    entity_id: input_number.hot_tub_target_temp
  action:
    - service: rest_command.hot_tub_command
      data:
        command: temp_set
        api_did: !secret hottub_api_did
        payload: "&temperature={{ states('input_number.hot_tub_target_temp') | int }}"
    - delay: 00:00:05
    - service: homeassistant.update_entity
      entity_id: sensor.hot_tub_status