automation:
- id: hot_tub_reset_target_temperature
  alias: Hot Tub - Reset target temperature to 35c
  trigger:
    platform: time
    at: "23:00"
  condition:
  - condition: numeric_state
    entity_id: input_number.hot_tub_target_temp
    above: 35
  action:
  - service: input_number.set_value
    target:
      entity_id: input_number.hot_tub_target_temp
    data:
      value: 35