sensor:
- platform: template
  sensors:
    hot_tub_temp_target:
      unique_id: hot_tub_temp_target
      availability_template: "{{ states('sensor.hot_tub_online') }}"
      friendly_name: "Hot Tub Target Temperature"
      unit_of_measurement: '°C'
      value_template: "{{ state_attr('sensor.hot_tub_api_status', 'temp_set') | int }}"
      icon_template: mdi:thermometer-plus
