switch:
- platform: template
  switches:
    hot_tub_power:
      availability_template: "{{ states('sensor.hot_tub_online') }}"
      unique_id: hot_tub_power
      friendly_name: Hot Tub Power
      icon_template: mdi:power
      value_template: >
        {% if state_attr('sensor.hot_tub_api_status', 'power') == 1 %}
          on
        {% else %}
          off
        {% endif %}
      turn_on:
        - service: rest_command.hot_tub_command
          data: 
            command: turn_on
            api_did: !secret hottub_api_did
            payload: ""
        - delay: 00:00:05
        - service: homeassistant.update_entity
          entity_id: sensor.hot_tub_api_status
      turn_off:
        - service: rest_command.hot_tub_command
          data: 
            command: turn_off
            api_did: !secret hottub_api_did
            payload: ""
        - delay: 00:00:05
        - service: homeassistant.update_entity
          entity_id: sensor.hot_tub_api_status