sensor:
- platform: rest
  resource: !secret wireguard_api_url
  name: WireGuard - Status
  unique_id: wireguard_peer_status
  value_template: "OK"
  icon: mdi:vpn
  json_attributes:
    - pete-iphone
    - sarah-iphone