light:
- platform: template
  lights:
    shed_workshop_workbench_lights:
      friendly_name: Shed Workshop Workbench Lights
      unique_id: shed_workshop_workbench_lights
      icon_template: mdi:wall-sconce-flat
      # value_template: >-
      #   {% if is_state('light.dummy_light', 'on') %}
      #     on
      #   {% else %}
      #     off
      #   {% endif %}
      turn_on:
        service: light.turn_on
        target:
          entity_id: light.dummy_light
      turn_off:
        service: light.turn_off
        target:
          entity_id: light.dummy_light