light:
- platform: template
  lights:
    shed_workshop_main_lights:
      friendly_name: Workshop - Main Lights
      unique_id: shed_workshop_main_lights
      icon_template: mdi:lightbulb-fluorescent-tube
      turn_on:
        service: light.turn_on
        target:
          entity_id: light.dummy_light
      turn_off:
        service: light.turn_off
        target:
          entity_id: light.dummy_light