# Lounge Sky Q
- platform: template
  switches:
    lounge_sky_q:
      friendly_name: Lounge Sky Q
      icon_template: mdi:satellite-variant
      value_template: "{{ not is_state('media_player.lounge_sky_q', 'off') }}"
      turn_on:
        service: media_player.turn_on
        data:
          entity_id: media_player.lounge_sky_q
      turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.lounge_sky_q

# Bedroom Sky Q
- platform: template
  switches:
    bedroom_sky_q:
      friendly_name: Bedroom Sky Q
      icon_template: mdi:satellite-variant
      value_template: "{{ not is_state('media_player.bedroom_sky_q', 'off') }}"
      turn_on:
        service: media_player.turn_on
        data:
          entity_id: media_player.bedroom_sky_q
      turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.bedroom_sky_q

# Lounge TV
- platform: template
  switches:
    lounge_tv:
      friendly_name: Lounge TV
      icon_template: mdi:television
      value_template: "{{ not is_state('media_player.lounge_tv', 'off') }}"
      turn_on:
        service: media_player.turn_on
        data:
          entity_id: media_player.lounge_tv
      turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.lounge_tv

# Bedroom TV
- platform: template
  switches:
    bedroom_tv:
      friendly_name: Bedroom TV
      icon_template: mdi:television
      value_template: "{{ not is_state('media_player.bedroom_tv', 'off') }}"
      turn_on:
        service: media_player.turn_on
        data:
          entity_id: media_player.bedroom_tv
      turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.bedroom_tv