automation:
- id: 'master_bedroom_turn_off_sky_if_tv_is_off'
  alias: Master Bedroom - Switch off Sky Q if TV has been turned off for 5 minutes
  trigger:
    entity_id: media_player.master_bedroom_tv
    platform: state
    to: 'off'
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition:
    condition: template
    value_template: "{% if not is_state('media_player.master_bedroom_sky_q', 'off') %}true{% endif %}"
  action:
  - entity_id: media_player.master_bedroom_sky_q
    service: media_player.turn_off
  mode: single
