light:
- platform: template
  lights:
    landing_stair_lights:
      friendly_name: Stair Lights
      unique_id: landing_stair_lights
      icon_template: mdi:chandelier
      turn_on:
        service: light.turn_on
        target:
          entity_id: light.dummy_light
      turn_off:
        service: light.turn_off
        target:
          entity_id: light.dummy_light
      set_level:
        service: input_number.set_value
        entity_id: input_number.dummy_input_number
        data:
          brightness: "{{ brightness }}"