automation:
- id: office_heating
  alias: Office - Turn heating on/off based on a schedule
  trigger:
  - platform: state
    entity_id:
    - schedule.office_heating
  condition: []
  action:
  - if:
    - condition: state
      entity_id: schedule.office_heating
      state: 'on'
    then:
    - service: climate.turn_on
      data: {}
      target:
        entity_id: climate.office
    else:
    - service: climate.turn_off
      data: {}
      target:
        entity_id: climate.office
  mode: single
