automation:
- id: office_heating_initialise
  alias: Office - Check if Office Heating should be 'on' at HA startup
  trigger:
    - platform: homeassistant
      event: start
  action:
    - if:
      - condition: state
        entity_id: schedule.office_heating
        state: "on"
      - condition: state
        entity_id: automation.office_turn_heating_on_off_based_on_a_schedule
        state: "on"
      then:
      - service: climate.turn_on
        data: {}
        target:
          entity_id: climate.office
      else:
      - service: climate.turn_on
        data: {}
        target:
          entity_id: climate.office
  mode: single