automation:
- id: front_garden_christmas_lights_on_at_dusk
  alias: Front Garden - Christmas Lights On At Dusk
  trigger:
    platform: sun
    event: sunset
    offset: "+00:15:00"
  action:
    service: homeassistant.turn_on
    entity_id: light.front_garden_christmas_lights