# Placeholder
light:
- platform: template
  lights:
    front_garden_side_lights:
      friendly_name: Front Garden - Side Lights
      unique_id: front_garden_side_lights
      icon_template: mdi:outdoor-lamp
      # value_template: >-
      #   {% if is_state('switch.front_garden_christmas_lights', 'on') %}
      #     on
      #   {% else %}
      #     off
      #   {% endif %}
      turn_on:
        service: light.turn_on
        target:
          entity_id: light.dummy_light
      turn_off:
        service: light.turn_off
        target:
          entity_id: light.dummy_light