switch:
- platform: template
  switches:
    front_garden_hall_light_switch:
      unique_id: front_garden_hall_light_switch
      friendly_name: Front Garden - Hall Light Switch
      icon_template: mdi:light-switch
      turn_on:
      - service: light.turn_on
        target:
          entity_id: light.front_garden_soffit_lights
      - service: light.turn_on
        target:
          entity_id: light.front_garden_side_lights
      turn_off:
      - service: light.turn_off
        target:
          entity_id: light.front_garden_soffit_lights
      - service: light.turn_off
        target:
          entity_id: light.front_garden_side_lights