automation:
- id: "hottub_initialise_target_temp"
  alias: "Initialise 'input_number.hottub_target_temp'"
  description: Set the initial value for 'input_number.hottub_target_temp' based on 'sensor.hottub_temp_target' when Home Assistant starts up
  trigger:
    - platform: homeassistant
      event: start
    - platform: numeric_state
      entity_id: sensor.hottub_temp_target
      above: input_number.hottub_target_temp
    - platform: numeric_state
      entity_id: sensor.hottub_temp_target
      below: input_number.hottub_target_temp
  action:
    service: input_number.set_value
    data_template:
      entity_id: input_number.hottub_target_temp
      value: "{{ states('sensor.hottub_temp_target') | int }}"    