automation:
- id: "20210519001"
  alias: "Set hot tub temperature"
  trigger:
    platform: state
    entity_id: input_number.hottub_target_temp
  action:
    - service: rest_command.hottub_temp_set
      data:
        api_did: !secret hottub_api_did
        temp: "{{ states('input_number.hottub_target_temp') | int }}"
    - delay: 00:00:05
    - service: homeassistant.update_entity
      entity_id: sensor.hottub_status