automation:
- id: "hottub_set_target_temp"
  alias: "Set hot tub temperature"
  description: Set the hot tub target temperature when 'input_number.hottub_target_temp' is changed
  trigger:
    platform: state
    entity_id: input_number.hottub_target_temp
  action:
    - service: rest_command.hottub_command
      data:
        command: temp_set
        api_did: !secret hottub_api_did
        payload: "&temperature={{ states('input_number.hottub_target_temp') | int }}"
    - delay: 00:00:05
    - service: homeassistant.update_entity
      entity_id: sensor.hottub_status