sensor:
  - platform: template
    sensors:
      hottub_error:
        availability_template: "{{ states('sensor.hottub_online') }}"
        friendly_name: "HotTub Error"
        icon_template: mdi:alert    
        value_template: >
          {% if ( state_attr('sensor.hottub_status','system_err1') | int  + state_attr('sensor.hottub_status','system_err2') | int  + state_attr('sensor.hottub_status','system_err3') | int  + state_attr('sensor.hottub_status','system_err4') | int  + state_attr('sensor.hottub_status','system_err5') | int  + state_attr('sensor.hottub_status','system_err6') | int  + state_attr('sensor.hottub_status','system_err7') | int  + state_attr('sensor.hottub_status','system_err8') | int  + state_attr('sensor.hottub_status','system_err9') | int  + state_attr('sensor.hottub_status','earth') | int ) > 0 %}
            on
          {% else %}
            off
          {% endif %}