sensor:
  - platform: template
    sensors:
      hottub_summary:
        availability_template: "{{ states('sensor.hottub_online') }}"
        friendly_name: "Hot Tub Status"
        value_template: >
          {% if is_state('sensor.hottub_online','false') %}
            Offline
          {% elif is_state('sensor.hottub_error','on') %}
            Error
          {% elif is_state('switch.hottub_bubbles','on') %}
            Bubbling
          {% elif states('sensor.hottub_temp_current') | int >= states('sensor.hottub_temp_target') | int %}
            Ready
          {% elif is_state('switch.hottub_heater','on') %}
            Heating
          {% elif is_state('switch.hottub_filter','on') %}
            Filtering
          {% elif is_state('switch.hottub_power','off') %}
            Switched Off
          {% else %}
            Unknown
          {% endif %}
        icon_template: >
          {% if is_state('sensor.hottub_online','false') %}
            mdi:wifi-off
          {% elif is_state('sensor.hottub_error','on') %}
            mdi:alert
          {% elif is_state('switch.hottub_bubbles','on') %}
            mdi:chart-bubble
          {% elif states('sensor.hottub_temp_current') | int >= states('sensor.hottub_temp_target') | int %}
            mdi:thermometer-lines
          {% elif is_state('switch.hottub_heater','on') %}
            mdi:fire
          {% elif is_state('switch.hottub_filter','on') %}
            mdi:air-filter
          {% elif is_state('switch.hottub_power','off') %}
            mdi:power
          {% else %}
            mdi:help-circle
          {% endif %}