sensor:
  - platform: template
    sensors:
      hottub_temp_target:
        availability_template: "{{ states('sensor.hottub_online') }}"
        friendly_name: "Hot Tub Target Temperature"
        unit_of_measurement: '°C'
        value_template: "{{ state_attr('sensor.hottub_status', 'temp_set') | int }}"      
