light:
- platform: template
  lights:
    lounge_floor_lamps:
      friendly_name: Lounge - Floor Lamps
      unique_id: lounge_floor_lamps
      icon_template: mdi:floor-lamp-dual
      turn_on:
        service: light.turn_on
        target:
          entity_id: light.dummy_light
      turn_off:
        service: light.turn_off
        target:
          entity_id: light.dummy_light