automation:
- id: 'back_garden_pergola_lights'
  alias: Back Garden - Pergola Lights - Toggle On/Off
  trigger:
    platform: event
    event_type: shelly.click
    event_data:
      device: shellyplus1-441793aaaa60
      channel: 1
      click_type: single_push
  condition: []
  action:
  - service: light.toggle
    target:
      entity_id: light.back_garden_pergola_lights
  mode: single
