automation:
- id: 'back_garden_hot_tub_lights'
  alias: Back Garden - Hot Tub Lights - Toggle On/Off
  trigger:
    platform: event
    event_type: shelly.click
    event_data:
      device: shellyplus1-441793aaaa60
      channel: 1
      click_type: single_push
  condition: []
  action:
  - service: light.toggle
    target:
      entity_id: light.back_garden_hot_tub_lights
  - service: switch.turn_off
    target:
      entity_id: switch.back_garden_hot_tub_lights_cycle
  mode: single
