automation:
- id: 'back_garden_hot_tub_lights_cycle'
  alias: Back Garden - Hot Tub Lights - Cycle Colours
  description: ""
  trigger:
    - platform: state
      entity_id:
        - switch.back_garden_hot_tub_lights_cycle
      to: "on"
  condition: []
  action:
    - service: light.turn_on
      data:
        hs_color:
          - 240
          - 100
      target:
        entity_id: light.back_garden_hot_tub_lights
    - repeat:
        until:
          - condition: not
            conditions:
              - condition: state
                entity_id: switch.back_garden_hot_tub_lights_cycle
                state: "on"
        sequence:
          - delay:
              hours: 0
              minutes: 0
              seconds: 0
              milliseconds: 500
          - service: light.turn_on
            data:
              hs_color:
                - '{{ (state_attr("light.back_garden_hot_tub_lights", "hs_color")[0] + 1) % 360 }}'
                - 100
            target:
              entity_id: light.back_garden_hot_tub_lights
    - service: light.turn_off
      target:
        entity_id: light.back_garden_hot_tub_lights
  mode: single