light:
- platform: group
  name: Back Garden - Hot Tub Lights
  unique_id: light_group_back_garden_hot_tub
  entities:
    - light.hot_tub_1
    - light.hot_tub_2
    - light.hot_tub_3
    - light.hot_tub_4