light:
- platform: template
  lights:
    back_garden_pergola_strips:
      friendly_name: Back Garden - Pergola Strips
      unique_id: back_garden_pergola_strips
      icon_template: mdi:led-strip-variant
      turn_on:
        service: light.turn_on
        target:
          entity_id: light.dummy_light
      turn_off:
        service: light.turn_off
        target:
          entity_id: light.dummy_light
      set_level:
        service: light.set_level
        target:
          entity_id: light.dummy_light
        data:
          brightness: "{{ brightness }}"
      set_color:
          - service: input_number.set_value
            data:
              value: "{{ h }}"
              entity_id: input_number.h_input
          - service: input_number.set_value
            data:
              value: "{{ s }}"
              entity_id: input_number.s_input
          - service: light.turn_on
            data_template:
              entity_id:
                - light.dummy_light
              transition: "{{ transition | float }}"
              hs_color:
                - "{{ hs[0] }}"
                - "{{ hs[1] }}"