light:
- platform: template
  lights:
    back_garden_wall_lights:
      friendly_name: Back Garden - Wall Lights
      unique_id: back_garden_wall_lights
      icon_template: mdi:post-lamp
      turn_on:
        service: light.turn_on
        target:
          entity_id: light.dummy_light
      turn_off:
        service: light.turn_off
        target:
          entity_id: light.dummy_light
      set_level:
        service: light.set_level
        target:
          entity_id: light.dummy_light
        data:
          brightness: "{{ brightness }}"