light:
- platform: group
  name: Back Garden - Pergola Spots
  unique_id: light_group_back_garden_pergola_spots
  entities:
    - light.back_garden_pergola_spot_1
    - light.back_garden_pergola_spot_2
    - light.back_garden_pergola_spot_3
    - light.back_garden_pergola_spot_4