light:
- platform: template
  lights:
    downstairs_bathroom_shower_alcove_light:
      friendly_name: Downstairs Bathroom - Shower Alcove Light
      unique_id: downstairs_bathroom_shower_alcove_light
      icon_template: mdi:shower-head
      # value_template: >-
      #   {% if is_state('light.dummy_light', 'on') %}
      #     on
      #   {% else %}
      #     off
      #   {% endif %}
      turn_on:
        service: light.turn_on
        target:
          entity_id: light.dummy_light
      turn_off:
        service: light.turn_off
        target:
          entity_id: light.dummy_light