light:
- platform: template
  lights:
    kitchen_plinth_lights:
      friendly_name: Kitchen - Plinth Lights
      unique_id: kitchen_plinth_lights
      icon_template: mdi:wall-sconce-round
      turn_on:
        service: light.turn_on
        target:
          entity_id: light.dummy_light
      turn_off:
        service: light.turn_off
        target:
          entity_id: light.dummy_light
      set_color:
          - service: input_number.set_value
            data:
              value: "{{ h }}"
              entity_id: input_number.h_input
          - service: input_number.set_value
            data:
              value: "{{ s }}"
              entity_id: input_number.s_input
          - service: light.turn_on
            data_template:
              entity_id:
                - light.dummy_light
              transition: "{{ transition | float }}"
              hs_color:
                - "{{ hs[0] }}"
                - "{{ hs[1] }}"