light:
- platform: template
  lights:
    kitchen_pendant_lights:
      friendly_name: Kitchen - Pendant Lights
      unique_id: kitchen_pendant_lights
      icon_template: mdi:ceiling-light
      # value_template: >-
      #   {% if is_state('light.dummy_light', 'on') %}
      #     on
      #   {% else %}
      #     off
      #   {% endif %}
      turn_on:
        service: light.turn_on
        target:
          entity_id: light.dummy_light
      turn_off:
        service: light.turn_off
        target:
          entity_id: light.dummy_light