automation:
- id: front_garden_soffit_lights_motion_triggered
  alias: Front Garden - Soffit Lights Motion Triggered
  trigger:
  - platform: state
    entity_id:
    - input_button.front_garden_soffit_lights_motion_sensor
  condition:
  - condition: not
    conditions:
    - condition: state
      entity_id: light.front_garden_soffit_lights
      state: 'on'
  action:
  - service: light.turn_on
    target:
      entity_id: light.front_garden_soffit_lights
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - service: light.turn_off
    target:
      entity_id: light.front_garden_soffit_lights
  mode: single
