# Placeholder
light:
- platform: template
  lights:
    front_garden_path_lights:
      friendly_name: Front Garden - Path Lights
      unique_id: front_garden_path_lights
      icon_template: mdi:outdoor-lamp
      turn_on:
        service: light.turn_on
        target:
          entity_id: light.dummy_light
      turn_off:
        service: light.turn_off
        target:
          entity_id: light.dummy_light