sensor:
- platform: template
  sensors:
    front_garden_path_last_motion:
      friendly_name: 'Front Garden - Path Last Motion'
      icon_template: mdi:motion-sensor
      entity_id:
        - sensor.time
      value_template: >
        {%- set time = (as_timestamp(now()) - as_timestamp(states.input_button.front_garden_path_motion_sensor.last_changed)) | int  %}
        {%- set minutes = ((time % 3600) // 60) %}
        {%- set minutes = '{} mins'.format(minutes) if minutes > 0 else '' %}
        {%- set hours = ((time % 86400) // 3600) %}
        {%- set hours = '{} hrs '.format(hours) if hours > 0 else '' %}
        {%- set days = (time // 86400) %}
        {%- set days = '{} days '.format(days) if days > 0 else '' %}
        {{ 'Less than 1 minute' if time < 60 else days + hours + minutes }} ago