sensor:
- platform: template
  sensors:
    front_garden_path_last_motion:
      friendly_name: 'Front Garden - Path Last Motion'
      icon_template: mdi:motion-sensor
      unique_id: front_garden_path_last_motion
      value_template: >
        {%- set seconds = (as_timestamp(now()) - as_timestamp(states.input_button.front_garden_path_motion_sensor.last_changed)) | int  %}
        {%- set minutes = ((seconds % 3600) / 60) | int %}
        {%- set hours = ((seconds % 86400) / 3600) | int %}
        {% set days = (seconds / 86400) | int %}

        {%- if seconds < 60 -%}
          < 1m
        {%- elif days > 0 -%}
          > 1d ago
        {%- else -%}
          {%- if hours > 0 -%}
            {{ hours }}h
          {%- endif -%}
          {%- if minutes > 0 -%}
            {%- if hours > 0 -%}
              {{ ' ' }}
            {%- endif -%}
            {{ minutes }}m
          {%- endif -%}
        {%- endif -%}
        {{ ' ' }}ago