light:
- platform: template
  lights:
    jacob_bedroom_spot_lights:
      friendly_name: Jacob - Spot Lights
      unique_id: jacob_bedroom_spot_lights
      icon_template: mdi:light-recessed
      turn_on:
        service: light.turn_on
        target:
          entity_id: light.dummy_light
      turn_off:
        service: light.turn_off
        target:
          entity_id: light.dummy_light