light:
- platform: template
  lights:
    downstairs_bathroom_main_lights:
      friendly_name: Downstairs Bathroom - Main Lights
      unique_id: downstairs_bathroom_main_lights
      icon_template: mdi:light-recessed
      turn_on:
        service: light.turn_on
        target:
          entity_id: light.dummy_light
      turn_off:
        service: light.turn_off
        target:
          entity_id: light.dummy_light