light:
- platform: template
  lights:
    georgia_bedroom_dressing_room_lights:
      friendly_name: Georgia - Dressing Room Lights
      unique_id: georgia_bedroom_dressing_room_lights
      icon_template: mdi:light-recessed
      turn_on:
        service: light.turn_on
        target:
          entity_id: light.dummy_light
      turn_off:
        service: light.turn_off
        target:
          entity_id: light.dummy_light