light:
- platform: template
  lights:
    georgia_bedroom_main_lights:
      friendly_name: Georgia - Main Lights
      unique_id: georgia_bedroom_main_lights
      icon_template: mdi:wall-sconce
      # value_template: >-
      #   {% if is_state('light.dummy_light', 'on') %}
      #     on
      #   {% else %}
      #     off
      #   {% endif %}
      turn_on:
        service: light.turn_on
        target:
          entity_id: light.dummy_light
      turn_off:
        service: light.turn_off
        target:
          entity_id: light.dummy_light
      set_level:
        service: light.set_level
        target:
          entity_id: light.dummy_light
        data:
          brightness: "{{ brightness }}"