light:
- platform: template
  lights:
    master_dressing_room_makeup_lights:
      friendly_name: Master Dressing Room - Makeup Lights
      unique_id: master_dressing_room_makeup_lights
      icon_template: mdi:light-recessed
      turn_on:
        service: light.turn_on
        target:
          entity_id: light.dummy_light
      turn_off:
        service: light.turn_off
        target:
          entity_id: light.dummy_light