light:
- platform: template
  lights:
    master_bathroom_shower_light:
      friendly_name: Master Bathroom - Shower Light
      unique_id: master_bathroom_shower_light
      icon_template: mdi:shower-head
      turn_on:
        service: light.turn_on
        target:
          entity_id: light.dummy_light
      turn_off:
        service: light.turn_off
        target:
          entity_id: light.dummy_light