sensor:
- platform: template
  sensors:
    ring_time_since_last_motion:
      friendly_name: 'Ring Last Motion'
      icon_template: mdi:motion-sensor
      unique_id: ring_time_since_last_motion
      value_template: >
        {%- set seconds = (as_timestamp(now()) - as_timestamp(states.sensor.front_door_last_motion.last_changed)) | int  %}
        {%- set minutes = ((seconds % 3600) / 60) | int %}
        {%- set hours = ((seconds % 86400) / 3600) | int %}
        {% set days = (seconds / 86400) | int %}

        {%- if seconds < 60 -%}
          Less than a minute ago
        {%- elif days > 0 -%}
          Over a day ago
        {%- else -%}
          {%- if hours > 0 -%}
            {{ hours }}h
          {%- endif -%}
          {%- if minutes > 0 -%}
            {%- if hours > 0 -%}
              {{ ' ' }}
            {%- endif -%}
            {{ minutes }}m
          {%- endif -%}
        {{ ' ' }}ago
        {%- endif -%}