sensor:
- platform: template
  sensors:
    ring_time_since_last_ding:
      friendly_name: 'Ring Last Ding'
      icon_template: mdi:bell-ring
      unique_id: ring_time_since_last_ding
      value_template: >
        {%- set seconds = (as_timestamp(now()) - as_timestamp(states.sensor.front_door_last_ding.last_changed)) | int  %}
        {%- set minutes = ((seconds % 3600) / 60) | int %}
        {%- set hours = ((seconds % 86400) / 3600) | int %}
        {%- set days = (seconds / 86400) | int %}

        {%- if days > 0 -%}
          > 1d
        {%- elif hours > 0 -%}
          {{ hours }}h {{ minutes }}m
        {%- elif minutes > 0 -%}
          {{ minutes }}m
        {%- else -%}
          < 1m
        {%- endif -%}
        {{ ' ' }}ago