sensor:
- platform: template
  sensors:
    ring_time_since_last_ding:
      friendly_name: 'Ring Last Ding'
      icon_template: mdi:bell-ring
      unique_id: ring_time_since_last_ding
      value_template: >
        {%- set seconds = (as_timestamp(now()) - as_timestamp(states.sensor.front_door_last_ding.last_changed)) | int  %}
        {%- set minutes = ((seconds % 3600) / 60) | int %}
        {%- set hours = ((seconds % 86400) / 3600) | int %}
        {% set days = (seconds / 86400) | int %}

        {%- if seconds < 60 -%}
          < 1m
        {%- elif days > 0 -%}
          > 1d ago
        {%- else -%}
          {%- if hours > 0 -%}
            {{ hours }}h
          {%- endif -%}
          {%- if minutes > 0 -%}
            {%- if hours > 0 -%}
              {{ ' ' }}
            {%- endif -%}
            {{ minutes }}m
          {%- endif -%}
        {%- endif -%}
        {{ ' ' }}ago