light:
- platform: template
  lights:
    back_garden_house_lights:
      friendly_name: Back Garden - House Lights
      unique_id: back_garden_house_lights
      icon_template: mdi:outdoor-lamp
      # value_template: >-
      #   {% if is_state('light.dummy_light', 'on') %}
      #     on
      #   {% else %}
      #     off
      #   {% endif %}
      turn_on:
        service: light.turn_on
        target:
          entity_id: light.dummy_light
      turn_off:
        service: light.turn_off
        target:
          entity_id: light.dummy_light