# Set up lighting groups
light:
- platform: group
  name: Master Suite - Lights
  unique_id: light_group_master_suite_all
  entities:
    - light.master_bathroom_lights
    - light.master_bedroom_lights
    - light.master_dressing_room_lights