light:
- platform: template
  lights:
    lounge_table_lamp:
      friendly_name: Lounge - Table Lamp
      unique_id: lounge_table_lamp
      icon_template: mdi:floor-lamp-dual
      value_template: >-
        {% if is_state('switch.lounge_table_lamp', 'on') %}
          on
        {% else %}
          off
        {% endif %}
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.lounge_table_lamp
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.lounge_table_lamp