light:
- platform: template
  lights:
    joshua_bedroom_main_lights:
      friendly_name: Joshua - Main Lights
      unique_id: joshua_bedroom_main_lights
      icon_template: mdi:ceiling-light
      turn_on:
        service: light.turn_on
        target:
          entity_id: light.dummy_light
      turn_off:
        service: light.turn_off
        target:
          entity_id: light.dummy_light
      set_level:
        service: light.set_level
        target:
          entity_id: light.dummy_light
        data:
          brightness: "{{ brightness }}"